# Generated by Django 3.1.1 on 2020-11-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201125_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_sale',
            field=models.IntegerField(default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='address',
            field=models.ImageField(upload_to='shop/images', verbose_name='图片地址'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='avatar',
            field=models.ImageField(upload_to='shop/images', verbose_name='logo'),
        ),
    ]
