# Generated by Django 3.1.1 on 2020-12-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.IntegerField(default=5, verbose_name='评分'),
            preserve_default=False,
        ),
    ]
