# Generated by Django 3.1.1 on 2020-12-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_comment_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('message_type', models.IntegerField(verbose_name='消息类型')),
                ('from_id', models.IntegerField(verbose_name='发送者')),
                ('to_id', models.IntegerField(verbose_name='接收人')),
                ('have_read', models.BooleanField(default=False, verbose_name='已读')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.IntegerField(default=0, verbose_name='销量'),
        ),
    ]
