# Generated by Django 3.1.1 on 2020-12-14 13:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 13, 14, 5, 821397, tzinfo=utc), verbose_name='生成时间'),
        ),
    ]
