# Generated by Django 3.1.1 on 2020-12-16 07:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_message_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 16, 7, 36, 43, 252576, tzinfo=utc), verbose_name='生成时间'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2020, 12, 16, 7, 36, 43, 252576, tzinfo=utc), verbose_name='创建时间')),
                ('end_time', models.DateTimeField(default=datetime.datetime(2020, 12, 16, 7, 36, 43, 252576, tzinfo=utc), verbose_name='截止时间')),
                ('discount', models.FloatField(verbose_name='优惠金额')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='所属商品')),
            ],
        ),
    ]
