# Generated by Django 3.1.4 on 2020-12-20 13:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20201216_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 13, 22, 7, 804489, tzinfo=utc), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 13, 22, 7, 804489, tzinfo=utc), verbose_name='截止时间'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 13, 22, 7, 803492, tzinfo=utc), verbose_name='生成时间'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.producttype', verbose_name='商品类型'),
        ),
    ]
