# Generated by Django 3.1.1 on 2020-12-23 07:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20201220_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 7, 17, 26, 669412, tzinfo=utc), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 7, 17, 26, 669412, tzinfo=utc), verbose_name='截止时间'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 7, 17, 26, 668415, tzinfo=utc), verbose_name='生成时间'),
        ),
        migrations.RemoveField(
            model_name='shop',
            name='type',
        ),
        migrations.AddField(
            model_name='shop',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.shoptype', verbose_name='店铺类型'),
        ),
    ]
