# Generated by Django 3.1.1 on 2020-12-24 04:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20201223_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 4, 29, 37, 704633, tzinfo=utc), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 4, 29, 37, 703635, tzinfo=utc), verbose_name='生成时间'),
        ),
    ]
