# Generated by Django 3.1.4 on 2020-12-24 09:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20201224_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 9, 23, 55, 959054, tzinfo=utc), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 9, 23, 55, 959054, tzinfo=utc), verbose_name='生成时间'),
        ),
    ]
