# Generated by Django 3.1.1 on 2020-12-25 04:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20201224_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='score',
            field=models.IntegerField(default=0, verbose_name='评分'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 4, 57, 10, 373532, tzinfo=utc), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 4, 57, 10, 372535, tzinfo=utc), verbose_name='生成时间'),
        ),
    ]
