# Generated by Django 3.1.1 on 2020-12-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201203_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=64, verbose_name='订单编号'),
        ),
    ]
